name: recover

on:
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
    - name: Restore
      run: |
        # tree -s /opt/actionarchivecache
        ls -lR /opt/actionarchivecache
