name: recover

on:
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
    - name: Restore
      run: |
        ls -l /opt/actionarchivecache
        ls -l /opt/hostedtoolcache
        
